import Head from "next/head";
import Link from "next/link";

const layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"/>
      </Head>
      <h3></h3>

      {children}
    </div>
  );
};

export default layout;
